# use postgresql
development:
  adapter: postgresql
  encoding: unicode
  database: task_manager_development
  pool: 5
  timeout: 5000
  username: root
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: task_manager_test
  pool: 5
  timeout: 5000
  username: root
  password:

production:
  adapter: postgresql
  database: task_manager_production
  pool: 5
  timeout: 501
  username: root
  password:
